### ISSUE TITLE
Corriger l’orthographe du nom de Denis

### ISSUE THREAD

**Issue by emchateau** [ouvroir/righettino#10]
Denis m’écris pour demander la correction de son nom sur la page du site
"Sur la page Righettino du site de l'ouvroir, pourrais-tu faire corriger l'orthographe de mon nom? C'est Ribouillault et non Ribouillaut."

**Comment by WilliamDiakite** [comment]
C'est corrigé (commité dans labouvroir) !

**Comment by emchateau** [comment]
merci
