### ISSUE TITLE
Storyboard

### ISSUE THREAD

**Issue by KenanOudin** [ouvroir/righettino#2]
Storyboard explaining the interactions present in the prototype on figma. 

Use of figma :

Concrete prototype showing the whole project and the operations to be done.

    Menu
    Metadata
    Operations

**Comment by WilliamDiakite** [comment]
16/08:

Emmanuel:
- image shouldn't be cut, items should be in their **context**,
- rewriting of the text : shouldn't go that direction
- a modal window with tabs to different parts of the text (ie. interpretation, transcription)

Kristine:
- Ok to have a roll over for items, but generally, items shouldn't be cropped,
- import to have a menu for the item
- movable text window (modal) : good idea, js components might already exist. Tabs is good touch
